### ISSUE TITLE
Job-components dep update causes a type mismatch in elasticsearch_bulk.

### ISSUE THREAD

**Issue by busma13** [terascope/elasticsearch-assets#1023]
Resolve a type error caused by updating job-components.

When bumping @terascope/job-components from 0.59.0 to 0.62.0 all tests fail with the following error:
```
Error: asset/src/elasticsearch_bulk/processor.ts(17,11): error TS2416: Property 'onBatch' in type 'ElasticsearchBulk' is not assignable to the same property in base type 'BatchProcessor<ElasticsearchBulkConfig>'.
```

Find and fix the type mismatch.

Ref:
#1020
